from pathlib import Path
root=Path('/mnt/data/v113_work')

# 1) Prisma schema: comment likes + admin hearts + reply metadata.
p=root/'backend/prisma/schema.prisma'
s=p.read_text()
s=s.replace('  reelComments        ReelComment[]         @relation("UserReelComments")\n', '  reelComments        ReelComment[]         @relation("UserReelComments")\n  commentLikes        CommentLike[]         @relation("UserCommentLikes")\n  reelCommentLikes    ReelCommentLike[]     @relation("UserReelCommentLikes")\n')
s=s.replace('  body      String\n  createdAt DateTime @default(now())\n  editedAt DateTime?\n  editCount Int @default(0)\n  post      Post', '  body      String\n  parentId  String?\n  adminLikes Int @default(0)\n  createdAt DateTime @default(now())\n  editedAt DateTime?\n  editCount Int @default(0)\n  post      Post')
s=s.replace('  author    User     @relation("UserComments", fields: [authorId], references: [id], onDelete: Cascade)\n\n  @@index([postId, createdAt])\n}\n\nmodel Like {', '  author    User     @relation("UserComments", fields: [authorId], references: [id], onDelete: Cascade)\n  likes     CommentLike[] @relation("CommentLikes")\n\n  @@index([postId, createdAt])\n  @@index([postId, adminLikes])\n}\n\nmodel CommentLike {\n  commentId String\n  userId    String\n  createdAt DateTime @default(now())\n  comment   Comment @relation("CommentLikes", fields: [commentId], references: [id], onDelete: Cascade)\n  user      User @relation("UserCommentLikes", fields: [userId], references: [id], onDelete: Cascade)\n  @@id([commentId, userId])\n  @@index([commentId, createdAt])\n}\n\nmodel Like {')
s=s.replace('  body String\n  createdAt DateTime @default(now())\n  editedAt DateTime?\n  editCount Int @default(0)\n  reel @relation', '  body String\n  parentId String?\n  adminLikes Int @default(0)\n  createdAt DateTime @default(now())\n  editedAt DateTime?\n  editCount Int @default(0)\n  reel @relation')
s=s.replace('  author User @relation("UserReelComments", fields:[authorId], references:[id], onDelete:Cascade)\n  @@index([reelId,createdAt])\n}\n\nmodel ReelFeedback', '  author User @relation("UserReelComments", fields:[authorId], references:[id], onDelete:Cascade)\n  likes ReelCommentLike[] @relation("ReelCommentLikes")\n  @@index([reelId,createdAt])\n  @@index([reelId,adminLikes])\n}\n\nmodel ReelCommentLike {\n  commentId String\n  userId String\n  createdAt DateTime @default(now())\n  comment ReelComment @relation("ReelCommentLikes", fields:[commentId], references:[id], onDelete:Cascade)\n  user User @relation("UserReelCommentLikes", fields:[userId], references:[id], onDelete:Cascade)\n  @@id([commentId,userId])\n  @@index([commentId,createdAt])\n}\n\nmodel ReelFeedback')
p.write_text(s)

# 2) Server schema compatibility additions.
p=root/'backend/src/server.js'
s=p.read_text()
needle='    `ALTER TABLE "Episode" ADD COLUMN IF NOT EXISTS "adminViews" INTEGER NOT NULL DEFAULT 0`,\n'
insert='''    `ALTER TABLE "Comment" ADD COLUMN IF NOT EXISTS "parentId" TEXT`,\n    `ALTER TABLE "Comment" ADD COLUMN IF NOT EXISTS "adminLikes" INTEGER NOT NULL DEFAULT 0`,\n    `ALTER TABLE "ReelComment" ADD COLUMN IF NOT EXISTS "parentId" TEXT`,\n    `ALTER TABLE "ReelComment" ADD COLUMN IF NOT EXISTS "adminLikes" INTEGER NOT NULL DEFAULT 0`,\n    `CREATE TABLE IF NOT EXISTS "CommentLike" ("commentId" TEXT NOT NULL,"userId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY ("commentId","userId"))`,\n    `CREATE INDEX IF NOT EXISTS "CommentLike_commentId_createdAt_idx" ON "CommentLike"("commentId","createdAt")`,\n    `CREATE TABLE IF NOT EXISTS "ReelCommentLike" ("commentId" TEXT NOT NULL,"userId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY ("commentId","userId"))`,\n    `CREATE INDEX IF NOT EXISTS "ReelCommentLike_commentId_createdAt_idx" ON "ReelCommentLike"("commentId","createdAt")`,\n'''
if needle not in s: raise SystemExit('schema needle not found')
s=s.replace(needle, needle+insert)

# 3) Replace post comment routes.
old="""app.patch('/api/posts/comments/:id',auth,async(req,res)=>{const c=await prisma.comment.findUnique({where:{id:req.params.id}});if(!c||c.authorId!==req.user.id)return res.status(403).json({error:'FORBIDDEN'});if(c.editCount>=1||Date.now()-c.createdAt.getTime()>5*60*1000)return res.status(400).json({error:'COMMENT_EDIT_WINDOW_EXPIRED'});const body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'EMPTY_COMMENT'});const out=await prisma.comment.update({where:{id:c.id},data:{body:body.slice(0,1000),editedAt:new Date(),editCount:{increment:1}}});res.json(out)});\napp.delete('/api/posts/comments/:id',auth,async(req,res)=>{const c=await prisma.comment.findUnique({where:{id:req.params.id},include:{post:true}});if(!c)return res.status(404).json({error:'NOT_FOUND'});if(c.authorId!==req.user.id&&c.post.authorId!==req.user.id)return res.status(403).json({error:'FORBIDDEN'});await prisma.comment.delete({where:{id:c.id}});res.json({ok:true})});\n\napp.post('/api/posts/:id/comments',auth,async(req,res)=>{const body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'EMPTY_COMMENT'});const p=await prisma.post.findUnique({where:{id:req.params.id}});if(!p)return res.status(404).json({error:'NOT_FOUND'});const c=await prisma.comment.create({data:{postId:p.id,authorId:req.user.id,body},include:{author:true}});if(p.authorId!==req.user.id)await prisma.notification.create({data:{userId:p.authorId,type:'COMMENT',text:'تم التعليق على منشورك'}});await notifyMentions(body,'تمت الإشارة إليك في تعليق على منشور');res.status(201).json({...c,author:safe(c.author)})});\napp.get('/api/posts/:id/comments',auth,async(req,res)=>{const rows=await prisma.comment.findMany({where:{postId:req.params.id},orderBy:{createdAt:'asc'},take:200,include:{author:true}});res.json(rows.map(c=>({...c,author:safe(c.author)})));});"""
new="""app.patch('/api/posts/comments/:id',auth,async(req,res)=>{const c=await prisma.comment.findUnique({where:{id:req.params.id}});if(!c||c.authorId!==req.user.id)return res.status(403).json({error:'FORBIDDEN'});if(c.editCount>=1||Date.now()-c.createdAt.getTime()>5*60*1000)return res.status(400).json({error:'COMMENT_EDIT_WINDOW_EXPIRED'});const body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'EMPTY_COMMENT'});const out=await prisma.comment.update({where:{id:c.id},data:{body:body.slice(0,1000),editedAt:new Date(),editCount:{increment:1}}});res.json(out)});\napp.delete('/api/posts/comments/:id',auth,async(req,res)=>{const c=await prisma.comment.findUnique({where:{id:req.params.id},include:{post:true}});if(!c)return res.status(404).json({error:'NOT_FOUND'});if(c.authorId!==req.user.id&&c.post.authorId!==req.user.id)return res.status(403).json({error:'FORBIDDEN'});await prisma.comment.delete({where:{id:c.id}});res.json({ok:true})});\napp.post('/api/posts/comments/:id/like',auth,async(req,res)=>{const id=req.params.id;const c=await prisma.comment.findUnique({where:{id},select:{id:true,authorId:true,adminLikes:true}});if(!c)return res.status(404).json({error:'NOT_FOUND'});const key={commentId:id,userId:req.user.id};const old=await prisma.commentLike.findUnique({where:{commentId_userId:key}});if(old)await prisma.commentLike.delete({where:{commentId_userId:key}});else{await prisma.commentLike.create({data:key});if(c.authorId!==req.user.id)await prisma.notification.create({data:{userId:c.authorId,type:'LIKE',text:'أعجب شخص بتعليقك'}}).catch(()=>{});}const likes=await prisma.commentLike.count({where:{commentId:id}});res.json({liked:!old,likeCount:likes+Number(c.adminLikes||0)});});\napp.post('/api/posts/:id/comments',auth,async(req,res)=>{const body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'EMPTY_COMMENT'});const p=await prisma.post.findUnique({where:{id:req.params.id}});if(!p)return res.status(404).json({error:'NOT_FOUND'});const parentId=String(req.body.parentId||'').trim()||null;const c=await prisma.comment.create({data:{postId:p.id,authorId:req.user.id,body:body.slice(0,1000),parentId},include:{author:true}});if(p.authorId!==req.user.id)await prisma.notification.create({data:{userId:p.authorId,type:'COMMENT',text:'تم التعليق على منشورك'}});await notifyMentions(body,'تمت الإشارة إليك في تعليق على منشور');res.status(201).json({...c,author:safe(c.author),likeCount:Number(c.adminLikes||0),likedByMe:false});});\napp.get('/api/posts/:id/comments',auth,async(req,res)=>{const rows=await prisma.comment.findMany({where:{postId:req.params.id},take:200,include:{author:true,likes:true},orderBy:[{adminLikes:'desc'},{createdAt:'asc'}]});res.json(rows.map(c=>({...c,author:safe(c.author),likeCount:c.likes.length+Number(c.adminLikes||0),likedByMe:c.likes.some(x=>x.userId===req.user.id)})));});"""
if old not in s: raise SystemExit('post comment block not found')
s=s.replace(old,new)

# 4) Replace reel comment routes.
old="""app.get('/api/reels/:id/comments',auth,async(req,res)=>{const cs=await prisma.reelComment.findMany({where:{reelId:req.params.id},include:{author:true},orderBy:{createdAt:'desc'},take:100});res.json(cs.map(c=>({...c,author:safe(c.author)})));});\napp.patch('/api/reels/comments/:id',auth,async(req,res)=>{const c=await prisma.reelComment.findUnique({where:{id:req.params.id}});if(!c||c.authorId!==req.user.id)return res.status(403).json({error:'FORBIDDEN'});if(c.editCount>=1||Date.now()-c.createdAt.getTime()>5*60*1000)return res.status(400).json({error:'COMMENT_EDIT_WINDOW_EXPIRED'});const body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'EMPTY_COMMENT'});res.json(await prisma.reelComment.update({where:{id:c.id},data:{body:body.slice(0,1000),editedAt:new Date(),editCount:{increment:1}}}))});\napp.delete('/api/reels/comments/:id',auth,async(req,res)=>{const c=await prisma.reelComment.findUnique({where:{id:req.params.id},include:{reel:true}});if(!c)return res.status(404).json({error:'NOT_FOUND'});if(c.authorId!==req.user.id&&c.reel.authorId!==req.user.id)return res.status(403).json({error:'FORBIDDEN'});await prisma.reelComment.delete({where:{id:c.id}});res.json({ok:true})});\napp.post('/api/reels/:id/comments',auth,async(req,res)=>{const body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'EMPTY_COMMENT'});const r=await prisma.reel.findUnique({where:{id:req.params.id}});if(!r)return res.status(404).json({error:'NOT_FOUND'});const c=await prisma.reelComment.create({data:{reelId:r.id,authorId:req.user.id,body:body.slice(0,1000)},include:{author:true}});if(r.authorId!==req.user.id)await prisma.notification.create({data:{userId:r.authorId,type:'COMMENT',text:'تم التعليق على الريلز الخاص بك'}});await notifyMentions(body,'تمت الإشارة إليك في تعليق على ريلز');res.status(201).json({...c,author:safe(c.author)});});"""
new="""app.get('/api/reels/:id/comments',auth,async(req,res)=>{const cs=await prisma.reelComment.findMany({where:{reelId:req.params.id},include:{author:true,likes:true},orderBy:[{adminLikes:'desc'},{createdAt:'asc'}],take:100});res.json(cs.map(c=>({...c,author:safe(c.author),likeCount:c.likes.length+Number(c.adminLikes||0),likedByMe:c.likes.some(x=>x.userId===req.user.id)})));});\napp.patch('/api/reels/comments/:id',auth,async(req,res)=>{const c=await prisma.reelComment.findUnique({where:{id:req.params.id}});if(!c||c.authorId!==req.user.id)return res.status(403).json({error:'FORBIDDEN'});if(c.editCount>=1||Date.now()-c.createdAt.getTime()>5*60*1000)return res.status(400).json({error:'COMMENT_EDIT_WINDOW_EXPIRED'});const body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'EMPTY_COMMENT'});res.json(await prisma.reelComment.update({where:{id:c.id},data:{body:body.slice(0,1000),editedAt:new Date(),editCount:{increment:1}}}))});\napp.delete('/api/reels/comments/:id',auth,async(req,res)=>{const c=await prisma.reelComment.findUnique({where:{id:req.params.id},include:{reel:true}});if(!c)return res.status(404).json({error:'NOT_FOUND'});if(c.authorId!==req.user.id&&c.reel.authorId!==req.user.id)return res.status(403).json({error:'FORBIDDEN'});await prisma.reelComment.delete({where:{id:c.id}});res.json({ok:true})});\napp.post('/api/reels/comments/:id/like',auth,async(req,res)=>{const id=req.params.id;const c=await prisma.reelComment.findUnique({where:{id},select:{id:true,authorId:true,adminLikes:true}});if(!c)return res.status(404).json({error:'NOT_FOUND'});const key={commentId:id,userId:req.user.id};const old=await prisma.reelCommentLike.findUnique({where:{commentId_userId:key}});if(old)await prisma.reelCommentLike.delete({where:{commentId_userId:key}});else{await prisma.reelCommentLike.create({data:key});if(c.authorId!==req.user.id)await prisma.notification.create({data:{userId:c.authorId,type:'LIKE',text:'أعجب شخص بتعليقك'}}).catch(()=>{});}const likes=await prisma.reelCommentLike.count({where:{commentId:id}});res.json({liked:!old,likeCount:likes+Number(c.adminLikes||0)});});\napp.post('/api/reels/:id/comments',auth,async(req,res)=>{const body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'EMPTY_COMMENT'});const r=await prisma.reel.findUnique({where:{id:req.params.id}});if(!r)return res.status(404).json({error:'NOT_FOUND'});const parentId=String(req.body.parentId||'').trim()||null;const c=await prisma.reelComment.create({data:{reelId:r.id,authorId:req.user.id,body:body.slice(0,1000),parentId},include:{author:true}});if(r.authorId!==req.user.id)await prisma.notification.create({data:{userId:r.authorId,type:'COMMENT',text:'تم التعليق على الريلز الخاص بك'}});await notifyMentions(body,'تمت الإشارة إليك في تعليق على ريلز');res.status(201).json({...c,author:safe(c.author),likeCount:Number(c.adminLikes||0),likedByMe:false});});"""
if old not in s: raise SystemExit('reel comment block not found')
s=s.replace(old,new)

# 5) Admin comments endpoint and boost hearts endpoint. Replace existing admin comments route.
old="app.get('/api/admin/comments',auth,admin,async(req,res)=>{const rows=await prisma.comment.findMany({orderBy:{createdAt:'desc'},take:300,include:{author:true,post:true}});res.json(rows.map(c=>({...c,author:safe(c.author)})));});"
new="""app.get('/api/admin/comments',auth,admin,async(req,res)=>{const kind=String(req.query.kind||'ALL').toUpperCase();const out=[];if(kind==='ALL'||kind==='POST'){const rows=await prisma.comment.findMany({orderBy:{createdAt:'desc'},take:300,include:{author:true,post:true,likes:true}});out.push(...rows.map(c=>({...c,kind:'POST',author:safe(c.author),likeCount:c.likes.length+Number(c.adminLikes||0)})));}if(kind==='ALL'||kind==='REEL'){const rows=await prisma.reelComment.findMany({orderBy:{createdAt:'desc'},take:300,include:{author:true,reel:true,likes:true}});out.push(...rows.map(c=>({...c,kind:'REEL',author:safe(c.author),likeCount:c.likes.length+Number(c.adminLikes||0)})));}out.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));res.json(out.slice(0,500));});\napp.post('/api/admin/comments/:kind/:id/boost',auth,requirePermission('comments.manage'),async(req,res)=>{try{const kind=String(req.params.kind||'').toUpperCase();const delta=Number(req.body?.hearts||0);if(!['POST','REEL'].includes(kind)||!Number.isInteger(delta)||delta===0||Math.abs(delta)>10000000)return res.status(400).json({error:'INVALID_HEART_DELTA'});let row;if(kind==='POST'){row=await prisma.comment.findUnique({where:{id:req.params.id}});if(!row)return res.status(404).json({error:'NOT_FOUND'});const next=Math.max(0,Number(row.adminLikes||0)+delta);row=await prisma.comment.update({where:{id:row.id},data:{adminLikes:next},include:{author:true,likes:true}});await auditAction(req,delta>0?'ADMIN_COMMENT_HEARTS_ADDED':'ADMIN_COMMENT_HEARTS_REMOVED',{permission:'comments.manage',targetId:row.id,targetType:'COMMENT',after:{kind,delta,adminLikes:next}});return res.json({...row,kind,author:safe(row.author),likeCount:row.likes.length+next});}row=await prisma.reelComment.findUnique({where:{id:req.params.id}});if(!row)return res.status(404).json({error:'NOT_FOUND'});const next=Math.max(0,Number(row.adminLikes||0)+delta);row=await prisma.reelComment.update({where:{id:row.id},data:{adminLikes:next},include:{author:true,likes:true}});await auditAction(req,delta>0?'ADMIN_COMMENT_HEARTS_ADDED':'ADMIN_COMMENT_HEARTS_REMOVED',{permission:'comments.manage',targetId:row.id,targetType:'REEL_COMMENT',after:{kind,delta,adminLikes:next}});res.json({...row,kind,author:safe(row.author),likeCount:row.likes.length+next});}catch(e){res.status(400).json({error:'COMMENT_HEART_UPDATE_FAILED'});}});"""
if old not in s: raise SystemExit('admin comments route not found')
s=s.replace(old,new)

# 6) Add achievements endpoint before creator milestones section.
marker='// ---- Creator milestones & rewards ----------------------------------------\n'
endpoint="""// ---- Achievements / tasks --------------------------------------------------\napp.get('/api/achievements',auth,async(req,res)=>{\n  const userId=req.user.id;\n  const [u,followers,following,posts,reels,comments,reelComments,lives,postLikes,reelLikes]=await Promise.all([\n    prisma.user.findUnique({where:{id:userId},select:{demoFollowersCount:true}}),\n    prisma.follow.count({where:{followingId:userId}}),\n    prisma.follow.count({where:{followerId:userId}}),\n    prisma.post.count({where:{authorId:userId}}),\n    prisma.reel.count({where:{authorId:userId}}),\n    prisma.comment.count({where:{authorId:userId}}),\n    prisma.reelComment.count({where:{authorId:userId}}),\n    prisma.liveRoom.count({where:{hostId:userId}}),\n    prisma.like.count({where:{post:{authorId:userId}}}),\n    prisma.reelLike.count({where:{reel:{authorId:userId}}}),\n  ]);\n  const followerCount=followers+Number(u?.demoFollowersCount||0);\n  const tasks=[\n    {id:'followers_100',title:'أول 100 متابع',description:'وصل إلى 100 متابع',target:100,progress:followerCount,rewardCoins:50,icon:'groups'},\n    {id:'followers_500',title:'صانع المجتمع',description:'وصل إلى 500 متابع',target:500,progress:followerCount,rewardCoins:150,icon:'groups'},\n    {id:'followers_1000',title:'مبدع مؤثر',description:'وصل إلى 1,000 متابع',target:1000,progress:followerCount,rewardCoins:300,icon:'verified'},\n    {id:'posts_10',title:'صانع المحتوى',description:'انشر 10 منشورات',target:10,progress:posts,rewardCoins:75,icon:'post'},\n    {id:'reels_10',title:'نجم Reels',description:'انشر 10 Reels',target:10,progress:reels,rewardCoins:100,icon:'movie'},\n    {id:'comments_25',title:'صوت المجتمع',description:'اكتب 25 تعليقًا',target:25,progress:comments+reelComments,rewardCoins:75,icon:'comment'},\n    {id:'live_3',title:'صاحب البث',description:'ابدأ 3 بثوث مباشرة',target:3,progress:lives,rewardCoins:150,icon:'live'},\n    {id:'likes_100',title:'محبوب المجتمع',description:'احصل على 100 إعجاب على محتواك',target:100,progress:postLikes+reelLikes,rewardCoins:200,icon:'heart'},\n    {id:'following_50',title:'شبكة واسعة',description:'تابع 50 حسابًا',target:50,progress:following,rewardCoins:50,icon:'people'},\n  ];\n  const newlyGranted=await grantCreatorMilestones(userId).catch(()=>[]);\n  res.json({followers:followerCount,tasks:tasks.map(x=>({...x,completed:x.progress>=x.target,ratio:x.target?Math.min(1,x.progress/x.target):1})),newlyGranted:newlyGranted.map(m=>({title:m.title,rewardCoins:m.rewardCoins,rewardGiftSlug:m.rewardGiftSlug,followersRequired:m.followersRequired}))});\n});\n\n"""
if marker not in s: raise SystemExit('marker not found')
s=s.replace(marker, endpoint+marker)

p.write_text(s)
