name: social_media_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  app_links: ^7.2.1
  archive: ^4.2.0
  audio_decoder: ^0.8.0
  audio_session: 0.1.25
  audioplayers: ^6.6.0
  cached_network_image: ^3.4.1
  characters: ^1.4.1
  collection: ^1.18.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  device_preview: ^1.2.0
  dio: ^5.9.2
  file_picker: ^10.3.8
  firebase_core: ^4.6.0
  firebase_crashlytics: ^5.4.0
  firebase_messaging: ^16.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_facebook_auth: ^7.1.5
  flutter_foreground_task: ^8.0.0
  flutter_highlight: ^0.7.0
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.2
  flutter_markdown_plus: ^1.0.12
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: 2.2.2
  font_awesome_flutter: ^11.0.0
  gal: ^2.3.2
  gap: ^3.0.1
  gif_view: ^1.0.3
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  image: ^4.5.4
  image_picker: ^1.2.1
  intl: 0.20.2
  linkify: ^5.0.0
  livekit_client: 2.5.3
  local_auth: ^2.3.0
  lottie: ^3.3.1
  markdown: ^7.0.0
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  persistent_bottom_nav_bar_v2: ^6.3.1
  receive_sharing_intent: 1.8.1
  record: ^6.2.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^12.0.0
  shared_preferences: 2.5.3
  shimmer: ^3.0.0
  speech_to_text: ^7.4.0
  story_view: ^0.16.6
  supabase_flutter: ^2.12.2
  url_launcher: ^6.3.2
  uuid: ^4.5.3
  video_player: 2.10.1
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  webview_flutter_android: ^4.13.0
  youtube_player_iframe: ^6.0.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  change_app_package_name: ^1.5.0
  fake_async: ^1.3.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

dependency_overrides:

  statemachine: 3.3.1
  file_picker: ^10.3.8
  permission_handler: ^11.3.1
  audio_session: 0.1.25
  analyzer: '>=8.0.0 <13.0.0'

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0D0D0D" 
  image: "assets/images/launcher.png"
  image_dark: "assets/images/launcher.png"
  android_12:
    color: "#FFFFFF"
    color_dark: "#0D0D0D"
    image: "assets/images/launcher.png"
    image_dark: "assets/images/launcher.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/inputAreaIcons/
    - assets/lotties/
    - assets/sounds/
    - assets/docs/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_24pt-Bold.ttf
          weight: 700

    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic/IBMPlexSansArabic-Bold.ttf
          weight: 700

    - family: NotoColorEmojiBundled
      fonts:
        - asset: assets/fonts/NotoColorEmoji/NotoColorEmoji-COLRv1.ttf
