import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../core/api.dart';
import '../core/theme.dart';
import '../core/widgets.dart';

class StorePage extends StatefulWidget {
  const StorePage({super.key});
  @override State<StorePage> createState() => _StorePageState();
}
class _StorePageState extends State<StorePage> {
  final search=TextEditingController(), location=TextEditingController(), min=TextEditingController(), max=TextEditingController();
  final cats=['الكل','ملابس','إلكترونيات','هدايا','رياضة'];
  String cat='الكل', sort='latest';
  late Future<List<dynamic>> future;
  @override void initState(){super.initState();future=_load();}
  Future<List<dynamic>> _load()=>Api.storeListings(category:cat,q:search.text.trim(),location:location.text.trim(),minPrice:min.text.trim(),maxPrice:max.text.trim(),sort:sort);
  void refresh()=>setState(()=>future=_load());
  @override void dispose(){search.dispose();location.dispose();min.dispose();max.dispose();super.dispose();}
  @override Widget build(BuildContext context){
    return Scaffold(
      backgroundColor:SN.bg0,
      appBar:AppBar(title:const Text('متجر SocialNova'),actions:[
        IconButton(onPressed:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const CreateListingPage()));refresh();},icon:const Icon(Icons.add_business_rounded,color:SN.green)),
        IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const StoreCommissionPage())),icon:const Icon(Icons.account_balance_wallet_rounded,color:SN.violet)),
      ]),
      body:Column(children:[
        Padding(padding:const EdgeInsets.all(12),child:TextField(controller:search,onSubmitted:(_)=>refresh(),decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'ابحث عن منتج...',suffixIcon:IconButton(onPressed:refresh,icon:const Icon(Icons.arrow_forward_rounded))))),
        SizedBox(height:48,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:12,vertical:5),itemCount:cats.length,separatorBuilder:(_,__)=>const SizedBox(width:7),itemBuilder:(_,i){final x=cats[i];return ChoiceChip(label:Text(x),selected:cat==x,onSelected:(_){setState(()=>cat=x);refresh();});})),
        Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:Row(children:[Expanded(child:OutlinedButton.icon(onPressed:_filters,icon:const Icon(Icons.tune_rounded),label:const Text('فلترة'))),const SizedBox(width:8),PopupMenuButton<String>(initialValue:sort,onSelected:(v){setState(()=>sort=v);refresh();},itemBuilder:(_)=>const [PopupMenuItem(value:'latest',child:Text('الأحدث')),PopupMenuItem(value:'popular',child:Text('الأكثر مشاهدة')),PopupMenuItem(value:'purchases',child:Text('الأكثر طلبًا'))],child:Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:SN.bg1,borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.sort_rounded)))])),
        Expanded(child:FutureBuilder<List<dynamic>>(future:future,builder:(context,snap){
          if(snap.connectionState==ConnectionState.waiting)return const LoadingBox();
          if(snap.hasError)return EmptyState(text:'${snap.error}'.replaceFirst('Exception: ',''),icon:Icons.store_mall_directory_outlined);
          final items=snap.data??[];
          if(items.isEmpty)return const EmptyState(text:'لا توجد منتجات مطابقة حاليًا',icon:Icons.inventory_2_outlined);
          return RefreshIndicator(onRefresh:()async{refresh();},child:GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,mainAxisSpacing:10,crossAxisSpacing:10,childAspectRatio:.68),itemCount:items.length,itemBuilder:(context,i){final item=Map<String,dynamic>.from(items[i] as Map);return StoreCard(item:item,onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>StoreDetailsPage(item:item))).then((_){refresh();}));}));
        }))
      ]),
    );
  }
  Future<void> _filters()async{await showModalBottomSheet(context:context,isScrollControlled:true,builder:(ctx)=>Padding(padding:EdgeInsets.fromLTRB(16,20,16,MediaQuery.of(ctx).viewInsets.bottom+20),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('فلترة المتجر',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:12),Row(children:[Expanded(child:TextField(controller:min,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'السعر من'))),const SizedBox(width:10),Expanded(child:TextField(controller:max,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'السعر إلى')))]),const SizedBox(height:10),TextField(controller:location,decoration:const InputDecoration(labelText:'الموقع')),const SizedBox(height:12),FilledButton(onPressed:(){Navigator.pop(ctx);refresh();},child:const Text('تطبيق'))])));}
}

class StoreCard extends StatelessWidget{const StoreCard({super.key,required this.item,required this.onTap});final Map<String,dynamic> item;final VoidCallback onTap;@override Widget build(BuildContext context){final image='${item['imageUrl']??''}',price=((item['finalPriceCents']??item['priceCents']??0)as num)/100;return InkWell(onTap:onTap,borderRadius:BorderRadius.circular(18),child:GlassCard(padding:EdgeInsets.zero,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:ClipRRect(borderRadius:const BorderRadius.vertical(top:Radius.circular(18)),child:image.isEmpty?Container(color:SN.bg3,child:const Center(child:Icon(Icons.shopping_bag_rounded,size:48,color:SN.gold))):Image.network(image,fit:BoxFit.cover,width:double.infinity,errorBuilder:(_,__,___)=>Container(color:SN.bg3,child:const Center(child:Icon(Icons.broken_image_outlined,size:40)))))),Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${item['title']}',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:5),Text('${price.toStringAsFixed(2)} ${item['currency']??'USD'}',style:const TextStyle(fontWeight:FontWeight.w900,color:SN.green)),const SizedBox(height:4),Text('${item['views']??0} مشاهدة',style:const TextStyle(fontSize:10,color:SN.textMut))]))])));}}
class StoreDetailsPage extends StatefulWidget{const StoreDetailsPage({super.key,required this.item});final Map<String,dynamic> item;@override State<StoreDetailsPage> createState()=>_StoreDetailsPageState();}
class _StoreDetailsPageState extends State<StoreDetailsPage>{bool busy=false;int qty=1;@override void initState(){super.initState();Api.storeView('${widget.item['id']}').catchError((_){return <String,dynamic>{};});}Future<void> order()async{setState(()=>busy=true);try{await Api.storeOrder('${widget.item['id']}',quantity:qty);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم تسجيل طلب الشراء بنجاح.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e'.replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> review() async {
   final c=TextEditingController(); int rating=5;
   await showDialog(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,set)=>AlertDialog(
     title:const Text('تقييم البائع'),
     content:Column(mainAxisSize:MainAxisSize.min,children:[
       DropdownButton<int>(value:rating,isExpanded:true,items:[1,2,3,4,5].map((x)=>DropdownMenuItem(value:x,child:Text('$x نجوم'))).toList(),onChanged:(x){if(x!=null)set(()=>rating=x);}),
       TextField(controller:c,maxLines:3,decoration:const InputDecoration(hintText:'مراجعتك (اختياري)')),
     ]),
     actions:[
       TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('إلغاء')),
       FilledButton(onPressed:()async{try{await Api.storeReview('${widget.item['id']}',rating:rating,comment:c.text);if(ctx.mounted)Navigator.pop(ctx);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حفظ التقييم.')));}catch(e){if(ctx.mounted)ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content:Text('$e'.replaceFirst('Exception: ',''))));}},child:const Text('إرسال')),
     ],
   )));
   c.dispose();
 }
 @override Widget build(BuildContext context){final i=widget.item;final image='${i['imageUrl']??''}';final price=((i['finalPriceCents']??i['priceCents']??0)as num)/100;return Scaffold(appBar:AppBar(title:const Text('تفاصيل المنتج')),body:ListView(padding:const EdgeInsets.all(12),children:[GlassCard(padding:EdgeInsets.zero,child:SizedBox(height:270,child:image.isEmpty?const Center(child:Icon(Icons.shopping_bag_rounded,size:80,color:SN.gold)):Image.network(image,fit:BoxFit.cover))),const SizedBox(height:12),Text('${i['title']}',style:const TextStyle(fontSize:23,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text('${i['description']??''}',style:const TextStyle(color:SN.textSec,height:1.45)),const SizedBox(height:12),Text('${price.toStringAsFixed(2)} ${i['currency']??'USD'}',style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:SN.green)),const SizedBox(height:12),Row(children:[IconButton(onPressed:qty>1?()=>setState(()=>qty--):null,icon:const Icon(Icons.remove_circle_outline)),Text('$qty',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18)),IconButton(onPressed:()=>setState(()=>qty++),icon:const Icon(Icons.add_circle_outline)),const Spacer(),Expanded(child:FilledButton.icon(onPressed:busy?null:order,icon:const Icon(Icons.shopping_cart_checkout),label:Text(busy?'جارٍ الطلب...':'طلب المنتج')))]),const SizedBox(height:8),OutlinedButton.icon(onPressed:review,icon:const Icon(Icons.rate_review_outlined),label:const Text('قيّم البائع بعد الشراء'))]));}}
class CreateListingPage extends StatefulWidget{const CreateListingPage({super.key});@override State<CreateListingPage> createState()=>_CreateListingPageState();}
class _CreateListingPageState extends State<CreateListingPage>{final title=TextEditingController(),desc=TextEditingController(),price=TextEditingController(),loc=TextEditingController(),coupon=TextEditingController(),discount=TextEditingController();String cat='ملابس';XFile? file;bool busy=false;@override void dispose(){for(final c in [title,desc,price,loc,coupon,discount])c.dispose();super.dispose();}Future<void> save()async{final p=double.tryParse(price.text);if(title.text.trim().length<2||p==null||p<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('أدخل اسم المنتج وسعرًا صحيحًا.')));return;}setState(()=>busy=true);try{String image='';if(file!=null){final r=await Api.uploadMedia(file!.path,kind:'IMAGE');image='${r['url']??''}';}await Api.createStoreListing({'title':title.text.trim(),'description':desc.text.trim(),'category':cat,'priceCents':(p*100).round(),'currency':'USD','location':loc.text.trim(),'imageUrl':image,'stock':1,'couponCode':coupon.text.trim(),'discountPct':int.tryParse(discount.text)??0});if(mounted)Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e'.replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('إضافة إعلان بيع')),body:ListView(padding:const EdgeInsets.all(14),children:[GlassCard(child:Column(children:[InkWell(onTap:()async{final x=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:88);if(x!=null)setState(()=>file=x);},child:Container(height:170,width:double.infinity,decoration:BoxDecoration(color:SN.bg3,borderRadius:BorderRadius.circular(16)),child:file==null?const Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.add_photo_alternate_outlined,size:48,color:SN.gold),SizedBox(height:7),Text('أضف صور المنتج')]):Image.file(File(file!.path),fit:BoxFit.cover))),const SizedBox(height:12),TextField(controller:title,decoration:const InputDecoration(labelText:'اسم المنتج')),const SizedBox(height:10),TextField(controller:desc,maxLines:4,decoration:const InputDecoration(labelText:'الوصف')),const SizedBox(height:10),DropdownButtonFormField<String>(value:cat,items:['ملابس','إلكترونيات','هدايا','رياضة'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x){if(x!=null)setState(()=>cat=x);}),const SizedBox(height:10),TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'السعر بالدولار')),const SizedBox(height:10),TextField(controller:loc,decoration:const InputDecoration(labelText:'الموقع')),const SizedBox(height:10),Row(children:[Expanded(child:TextField(controller:coupon,decoration:const InputDecoration(labelText:'كود الخصم'))),const SizedBox(width:10),Expanded(child:TextField(controller:discount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'خصم %')))]),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:busy?null:save,icon:const Icon(Icons.publish_rounded),label:Text(busy?'جارٍ النشر...':'نشر الإعلان')))]))]));
}
class StoreCommissionPage extends StatefulWidget{const StoreCommissionPage({super.key});@override State<StoreCommissionPage> createState()=>_StoreCommissionPageState();}
class _StoreCommissionPageState extends State<StoreCommissionPage>{late Future<Map<String,dynamic>> future;@override void initState(){super.initState();future=Api.storeCommissionDashboard();}String money(dynamic c)=>'${((c??0)as num)/100} USD';@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('العمولات والأرباح')),body:FutureBuilder<Map<String,dynamic>>(future:future,builder:(context,s){if(s.connectionState==ConnectionState.waiting)return const LoadingBox();if(s.hasError)return const EmptyState(text:'تعذر تحميل تقرير العمولات',icon:Icons.analytics_outlined);final d=s.data??{},sum=Map<String,dynamic>.from(d['summary']??{}),settings=Map<String,dynamic>.from(d['settings']??{});return ListView(padding:const EdgeInsets.all(12),children:[GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('نظام العمولات',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text('عمولة المبيعات الحالية: ${settings['saleRatePct']??5}%'),Text('عمولة الإحالة: ${settings['affiliateRatePct']??2}%')])),const SizedBox(height:10),Text('الإجمالي: ${money(sum['grossCents'])}'),Text('عمولة المنصة: ${money(sum['commissionCents'])}'),Text('صافي البائع: ${money(sum['netCents'])}'),Text('عمولات الإحالة: ${money(sum['affiliateCents'])}')]);}));}
