import 'package:flutter/material.dart';

/// Semantic color palette definition for the Social Mate Design System.
///
/// Contains all semantic roles (Primary, Surface, Background, Outlines, Status, etc.)
/// and supports all 12 dynamic themes in both Light and Dark modes.
@immutable
class AppPalette {
  final Color primary;
  final Color primaryContainer;
  final Color onPrimary;
  final Color secondary;
  final Color background;
  final Color surface;
  final Color surfaceElevated;
  final Color surfaceVariant;
  final Color onSurface;
  final Color onSurfaceVariant;
  final Color outline;
  final Color outlineVariant;
  final Color error;
  final Color errorContainer;
  final Color success;
  final Color warning;
  final Color scrim;
  final Brightness brightness;

  const AppPalette({
    required this.primary,
    required this.primaryContainer,
    required this.onPrimary,
    required this.secondary,
    required this.background,
    required this.surface,
    required this.surfaceElevated,
    required this.surfaceVariant,
    required this.onSurface,
    required this.onSurfaceVariant,
    required this.outline,
    required this.outlineVariant,
    required this.error,
    required this.errorContainer,
    required this.success,
    required this.warning,
    this.scrim = const Color(0x80000000),
    required this.brightness,
  });

  bool get isDark => brightness == Brightness.dark;

  /// Converts this semantic palette into a standard Material 3 [ColorScheme].
  ColorScheme toColorScheme() {
    return ColorScheme(
      brightness: brightness,
      primary: primary,
      onPrimary: onPrimary,
      primaryContainer: primaryContainer,
      onPrimaryContainer:
          isDark ? const Color(0xFFDBEAFE) : const Color(0xFF1E3A5F),
      secondary: secondary,
      onSecondary: isDark ? const Color(0xFF111827) : const Color(0xFFFFFFFF),
      error: error,
      onError: isDark ? const Color(0xFF111827) : const Color(0xFFFFFFFF),
      errorContainer: errorContainer,
      onErrorContainer:
          isDark ? const Color(0xFFFEE2E2) : const Color(0xFF7F1D1D),
      surface: surface,
      onSurface: onSurface,
      surfaceContainerHighest: surfaceVariant,
      onSurfaceVariant: onSurfaceVariant,
      outline: outline,
      outlineVariant: outlineVariant,
      scrim: scrim,
    );
  }
}

/// Static color constants, default palettes, and theme mapping for all 12 themes.
abstract final class AppColors {
  // --- Universal Status & Accent Colors ---

  /// Success green (Online status, positive actions)
  static const Color successLight = Color(0xFF10B981);
  static const Color successDark = Color(0xFF34D399);

  /// Warning amber (Pending states, notices)
  static const Color warningLight = Color(0xFFF59E0B);
  static const Color warningDark = Color(0xFFFBBF24);

  /// Error red (Destructive actions, error states)
  static const Color errorLight = Color(0xFFEF4444);
  static const Color errorDark = Color(0xFFF87171);
  static const Color errorContainerLight = Color(0xFFFEE2E2);
  static const Color errorContainerDark = Color(0xFF450A0A);

  /// Scrim overlay (50% black)
  static const Color scrim = Color(0x80000000);

  // --- Reference Theme Palettes (Ocean - Default) ---

  static const AppPalette oceanLight = AppPalette(
    brightness: Brightness.light,
    primary: Color(0xFF2563EB),
    primaryContainer: Color(0xFFDBEAFE),
    onPrimary: Color(0xFFFFFFFF),
    secondary: Color(0xFF6B7280),
    background: Color(0xFFFAFBFC),
    surface: Color(0xFFFFFFFF),
    surfaceElevated: Color(0xFFFFFFFF),
    surfaceVariant: Color(0xFFF0F6FA),
    onSurface: Color(0xFF111827),
    onSurfaceVariant: Color(0xFF6B7280),
    outline: Color(0xFFE2E8F0),
    outlineVariant: Color(0xFFEDF2F7),
    error: errorLight,
    errorContainer: errorContainerLight,
    success: successLight,
    warning: warningLight,
  );

  /// Ocean Dark Palette
  static const AppPalette oceanDark = AppPalette(
    brightness: Brightness.dark,
    primary: Color(0xFF389BFF),
    primaryContainer: Color(0xFF0C3666),
    onPrimary: Color(0xFFFFFFFF),
    secondary: Color(0xFF9CA3AF),
    background: Color(0xFF0F1115),
    surface: Color(0xFF1A1D23),
    surfaceElevated: Color(0xFF22262E),
    surfaceVariant: Color(0xFF262A33),
    onSurface: Color(0xFFF9FAFB),
    onSurfaceVariant: Color(0xFF9CA3AF),
    outline: Color(0xFF374151),
    outlineVariant: Color(0xFF1F2937),
    error: errorDark,
    errorContainer: errorContainerDark,
    success: successDark,
    warning: warningDark,
  );

  // --- Palettes for all 12 Themes ---

  static const Map<String, AppPalette> lightPalettes = {
    'ocean': oceanLight,
    'sunset': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFFEA580C),
      primaryContainer: Color(0xFFFFEDD5),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF78716C),
      background: Color(0xFFFFFBF5),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFF5F0E6),
      onSurface: Color(0xFF1C1917),
      onSurfaceVariant: Color(0xFF78716C),
      outline: Color(0xFFE7E5E4),
      outlineVariant: Color(0xFFF5F5F4),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'forest': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFF16A34A),
      primaryContainer: Color(0xFFDCFCE7),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF6B7280),
      background: Color(0xFFF5FAF7),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFEBF4EE),
      onSurface: Color(0xFF111827),
      onSurfaceVariant: Color(0xFF6B7280),
      outline: Color(0xFFE5E7EB),
      outlineVariant: Color(0xFFF3F4F6),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'midnight': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFF7C3AED),
      primaryContainer: Color(0xFFEDE9FE),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF6B7280),
      background: Color(0xFFF5F3FF),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFEDE9FE),
      onSurface: Color(0xFF111827),
      onSurfaceVariant: Color(0xFF6B7280),
      outline: Color(0xFFE5E7EB),
      outlineVariant: Color(0xFFF3F4F6),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'gold': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFFB8860B),
      primaryContainer: Color(0xFFFEF3C7),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF78716C),
      background: Color(0xFFFDFAF3),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFF5EFE0),
      onSurface: Color(0xFF1C1917),
      onSurfaceVariant: Color(0xFF78716C),
      outline: Color(0xFFE7E5E4),
      outlineVariant: Color(0xFFF5F5F4),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'glass': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFF475569),
      primaryContainer: Color(0xFFE2E8F0),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF64748B),
      background: Color(0xFFF8FAFC),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFF1F5F9),
      onSurface: Color(0xFF0F172A),
      onSurfaceVariant: Color(0xFF64748B),
      outline: Color(0xFFCBD5E1),
      outlineVariant: Color(0xFFE2E8F0),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'lavender': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFF7C3AED),
      primaryContainer: Color(0xFFF3E8FF),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF6B7280),
      background: Color(0xFFFAF5FF),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFF3E8FF),
      onSurface: Color(0xFF111827),
      onSurfaceVariant: Color(0xFF6B7280),
      outline: Color(0xFFE5E7EB),
      outlineVariant: Color(0xFFF3F4F6),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'carbon': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFF06B6D4),
      primaryContainer: Color(0xFFCFFAFE),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF6B7280),
      background: Color(0xFFF0FDFA),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFE0F2FE),
      onSurface: Color(0xFF111827),
      onSurfaceVariant: Color(0xFF6B7280),
      outline: Color(0xFFE5E7EB),
      outlineVariant: Color(0xFFF3F4F6),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'emerald': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFF059669),
      primaryContainer: Color(0xFFD1FAE5),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF6B7280),
      background: Color(0xFFF0FDF4),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFDCFCE7),
      onSurface: Color(0xFF111827),
      onSurfaceVariant: Color(0xFF6B7280),
      outline: Color(0xFFE5E7EB),
      outlineVariant: Color(0xFFF3F4F6),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'nordic': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFFBE185D),
      primaryContainer: Color(0xFFFCE7F3),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF6B7280),
      background: Color(0xFFFDF2F8),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFFCE7F3),
      onSurface: Color(0xFF111827),
      onSurfaceVariant: Color(0xFF6B7280),
      outline: Color(0xFFE5E7EB),
      outlineVariant: Color(0xFFF3F4F6),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'grape': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFF9333EA),
      primaryContainer: Color(0xFFF3E8FF),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF6B7280),
      background: Color(0xFFFAF5FF),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFEDE9FE),
      onSurface: Color(0xFF111827),
      onSurfaceVariant: Color(0xFF6B7280),
      outline: Color(0xFFE5E7EB),
      outlineVariant: Color(0xFFF3F4F6),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
    'sahara': AppPalette(
      brightness: Brightness.light,
      primary: Color(0xFFB45309),
      primaryContainer: Color(0xFFFEF3C7),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF78716C),
      background: Color(0xFFFFFBEB),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFFFEF3C7),
      onSurface: Color(0xFF1C1917),
      onSurfaceVariant: Color(0xFF78716C),
      outline: Color(0xFFE7E5E4),
      outlineVariant: Color(0xFFF5F5F4),
      error: errorLight,
      errorContainer: errorContainerLight,
      success: successLight,
      warning: warningLight,
    ),
  };

  static const Map<String, AppPalette> darkPalettes = {
    'ocean': oceanDark,
    'sunset': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFFFB923C),
      primaryContainer: Color(0xFF431407),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFA8A29E),
      background: Color(0xFF151210),
      surface: Color(0xFF1F1A17),
      surfaceElevated: Color(0xFF29221E),
      surfaceVariant: Color(0xFF2E2621),
      onSurface: Color(0xFFFAFAF9),
      onSurfaceVariant: Color(0xFFA8A29E),
      outline: Color(0xFF44403C),
      outlineVariant: Color(0xFF292524),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'forest': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFF4ADE80),
      primaryContainer: Color(0xFF052E16),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF9CA3AF),
      background: Color(0xFF0D1410),
      surface: Color(0xFF141F19),
      surfaceElevated: Color(0xFF1B2A22),
      surfaceVariant: Color(0xFF203228),
      onSurface: Color(0xFFF9FAFB),
      onSurfaceVariant: Color(0xFF9CA3AF),
      outline: Color(0xFF374151),
      outlineVariant: Color(0xFF1F2937),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'midnight': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFFA78BFA),
      primaryContainer: Color(0xFF2E1065),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF9CA3AF),
      background: Color(0xFF0E0B1A),
      surface: Color(0xFF161228),
      surfaceElevated: Color(0xFF1E1936),
      surfaceVariant: Color(0xFF241E42),
      onSurface: Color(0xFFF9FAFB),
      onSurfaceVariant: Color(0xFF9CA3AF),
      outline: Color(0xFF374151),
      outlineVariant: Color(0xFF1F2937),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'gold': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFFDAA520),
      primaryContainer: Color(0xFF451A03),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFA8A29E),
      background: Color(0xFF141210),
      surface: Color(0xFF1E1A17),
      surfaceElevated: Color(0xFF28231E),
      surfaceVariant: Color(0xFF302A24),
      onSurface: Color(0xFFFAFAF9),
      onSurfaceVariant: Color(0xFFA8A29E),
      outline: Color(0xFF44403C),
      outlineVariant: Color(0xFF292524),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'glass': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFF94A3B8),
      primaryContainer: Color(0xFF1E293B),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF94A3B8),
      background: Color(0xFF0F1114),
      surface: Color(0xFF181C22),
      surfaceElevated: Color(0xFF20252D),
      surfaceVariant: Color(0xFF262C36),
      onSurface: Color(0xFFF8FAFC),
      onSurfaceVariant: Color(0xFF94A3B8),
      outline: Color(0xFF334155),
      outlineVariant: Color(0xFF1E293B),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'lavender': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFFA78BFA),
      primaryContainer: Color(0xFF3B0764),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF9CA3AF),
      background: Color(0xFF110D19),
      surface: Color(0xFF1A1426),
      surfaceElevated: Color(0xFF231B33),
      surfaceVariant: Color(0xFF2C2240),
      onSurface: Color(0xFFF9FAFB),
      onSurfaceVariant: Color(0xFF9CA3AF),
      outline: Color(0xFF374151),
      outlineVariant: Color(0xFF1F2937),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'carbon': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFF22D3EE),
      primaryContainer: Color(0xFF083344),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF9CA3AF),
      background: Color(0xFF0A0A0A),
      surface: Color(0xFF141414),
      surfaceElevated: Color(0xFF1E1E1E),
      surfaceVariant: Color(0xFF242424),
      onSurface: Color(0xFFF9FAFB),
      onSurfaceVariant: Color(0xFF9CA3AF),
      outline: Color(0xFF2E2E2E),
      outlineVariant: Color(0xFF1F1F1F),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'emerald': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFF34D399),
      primaryContainer: Color(0xFF064E3B),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF9CA3AF),
      background: Color(0xFF0A120E),
      surface: Color(0xFF101E17),
      surfaceElevated: Color(0xFF162A20),
      surfaceVariant: Color(0xFF1C3428),
      onSurface: Color(0xFFF9FAFB),
      onSurfaceVariant: Color(0xFF9CA3AF),
      outline: Color(0xFF2D4A3E),
      outlineVariant: Color(0xFF1F332B),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'nordic': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFFF472B6),
      primaryContainer: Color(0xFF500724),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF9CA3AF),
      background: Color(0xFF140E12),
      surface: Color(0xFF1F161C),
      surfaceElevated: Color(0xFF2A1E26),
      surfaceVariant: Color(0xFF33242E),
      onSurface: Color(0xFFF9FAFB),
      onSurfaceVariant: Color(0xFF9CA3AF),
      outline: Color(0xFF4B2E40),
      outlineVariant: Color(0xFF331F2B),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'grape': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFFC084FC),
      primaryContainer: Color(0xFF3B0764),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF9CA3AF),
      background: Color(0xFF0E0A17),
      surface: Color(0xFF181126),
      surfaceElevated: Color(0xFF211736),
      surfaceVariant: Color(0xFF2A1D45),
      onSurface: Color(0xFFF9FAFB),
      onSurfaceVariant: Color(0xFF9CA3AF),
      outline: Color(0xFF374151),
      outlineVariant: Color(0xFF1F2937),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
    'sahara': AppPalette(
      brightness: Brightness.dark,
      primary: Color(0xFFD97706),
      primaryContainer: Color(0xFF451A03),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFA8A29E),
      background: Color(0xFF14110D),
      surface: Color(0xFF1F1A14),
      surfaceElevated: Color(0xFF29231B),
      surfaceVariant: Color(0xFF332B22),
      onSurface: Color(0xFFFAFAF9),
      onSurfaceVariant: Color(0xFFA8A29E),
      outline: Color(0xFF44403C),
      outlineVariant: Color(0xFF292524),
      error: errorDark,
      errorContainer: errorContainerDark,
      success: successDark,
      warning: warningDark,
    ),
  };

  /// Retrieves the [AppPalette] for a given theme name and brightness.
  static AppPalette getPalette(String themeName, {required bool isDark}) {
    final map = isDark ? darkPalettes : lightPalettes;
    return map[themeName.toLowerCase()] ?? (isDark ? oceanDark : oceanLight);
  }
}
